runtime: nodejs20 # or nodejs18, based on your Node version

entrypoint: npm run start

env_variables:
  NODE_ENV: "production"

instance_class: F2 # optional: controls resources

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
